#ifndef _WORKSPACE_H
#define _WORKSPACE_H

	defc WORKSPACE_ACIA = RAM_START

	defc ACIA_BUFFER_SIZE = 256
	defc ACIA_BUFFER_LO = 8
	defc ACIA_BUFFER_HI = ACIA_BUFFER_SIZE - 16

	defc ACIA_RX_BUFFER = WORKSPACE_ACIA
	defc ACIA_RX_HEAD = ACIA_RX_BUFFER + ACIA_BUFFER_SIZE
	defc ACIA_RX_TAIL = ACIA_RX_HEAD + 2
	defc ACIA_RX_LENGTH = ACIA_RX_TAIL + 2
	defc ACIA_TX_LAST = ACIA_RX_LENGTH + 1
	defc ACIA_CTRL_REG = ACIA_TX_LAST + 1
	defc WORKSPACE_ACIA_SIZE = ACIA_CTRL_REG + 1 - WORKSPACE_ACIA

	defc WORKSPACE_BASIC = RAM_START + WORKSPACE_ACIA_SIZE

#endif